language: python
python:
- 3.5.1
script:
- python examples/validate.py
before_deploy:
- python find-latest-schemas.py schemas/ schemas-latest/
- tar -zcvf event-types-all.tar.gz schemas/*
- tar -zcvf event-types-latest.tar.gz schemas-latest/*
deploy:
  provider: releases
  api-key:
    secure: b6VF37Wa/KOATvIN+SSB3gRUJg14O+88Fa26x+5oVNZd/SBJQmwOGVRSRS+o5hYzqHHR/XvSSXAzGjeujcZvFF+wahUHa8NCOf+v9vBnRSCtS8iDG5LboHlUTf33veSUJTOhWWScXcLJdeVPgzA2ON13/py+SwEqH/Dq1zpZAgdsSs6qHjMmFy3arD52r9KQOWiaWEYUZ1zf4zlHSz++7kaO5nnsmqGzsJZ9sHgM9bL8hngB3+awU4BimiScYBB8bEse5ibgOD58k89ux9ll8esSh+JZmQmbAB4quDBCjmly4P8Nd+KXFTvjSNMv7s4lSGN7Oin0GtSuWWfuZRlzUde2kTuI22a8LE+msU+t+CBPkmaKiQK7CDKfT5vDhgy8fugeyNNhVDtU0W0FQ5mR7C2I6URsnHj2goQMr/8VWxDIcdaO+8N1lv7hHf128BWny4xvPxBKIqvpEYlUkM+SGA3a67SiPCEgCSv3P7ZEJZhp5K8tj/2N9PLI70rfXML7gA3Cdf9drvZ+ukUmfZczQkZWFoT7+2ncaUGQ2Lxu8uI6MaMKlbC2Mxg0lVuUzoLgejTU/kfRXzc6cUq2oOez/7emZu7i4s1dbpU0Gv1DxAmmOfIlJPPt8JDgRFSA/TThhjOnly5EhL+zkPbSqbsD6YA77xmtLT8JUtvF4IDQPJU=
  file:
  - event-types-all.tar.gz
  - event-types-latest.tar.gz
  skip_cleanup: true
  on:
    repo: Ericsson/eiffel-operations-extension
    tags: true
